version: '3.5'

services:
  openiddict-api:
    container_name: openiddict-api
    image: openiddict-api
    build:
      context: .
      dockerfile: ./src/OpeniddictSample.Api/Dockerfile
      target: openiddict-api
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
  openiddict-id:
    container_name: openiddict-id
    image: openiddict-id
    build:
      context: .
      dockerfile: ./src/OpeniddictSample.Id/Dockerfile
      target: openiddict-id
    ports:
      - "5002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      CONNECTIONSTRING: "Host=openiddict-sample-db;Port=5432;Database=openiddict_sample_db;Username=dev;Password=dev;Include Error Detail=true"
    depends_on:
      - openiddict-id-db
  openiddict-id-db:
    container_name: openiddict-id-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
