version: '3.5'

services:
  openiddict-api:
    container_name: openiddict-api
    image: openiddict-api
    build:
      context: .
      dockerfile: ./src/OpeniddictSample.Api/Dockerfile
      target: openiddict-api
    ports:
      - "5001:80"
      - "5002:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_HTTPS_PORTS: 443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  openiddict-id:
    container_name: openiddict-id
    image: openiddict-id
    build:
      context: .
      dockerfile: ./src/OpeniddictSample.Id/Dockerfile
      target: openiddict-id
    ports:
      - "5003:80"
      - "5004:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      ASPNETCORE_HTTPS_PORTS: 443
      CONNECTIONSTRINGS__OPENIDDICT_ID_DB: "Host=openiddict-id-db;Port=5432;Database=openiddict_sample_db;Username=dev;Password=dev;Include Error Detail=true"
    depends_on:
      - openiddict-id-db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  openiddict-id-db:
    container_name: openiddict-id-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
