version: '3.5'

services:
  survey-app:
    container_name: openiddict-sample-id
    image: openiddict-sample-id
    build:
      context: .
      dockerfile: ./src/OpeniddictSample.Id/Dockerfile
      target: openiddict-sample-id
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      CONNECTIONSTRING: "Host=openiddict-sample-db;Port=5432;Database=openiddict_sample_db;Username=dev;Password=dev;Include Error Detail=true"
    depends_on:
      - openiddict-sample-db
  openiddict-sample-db:
    container_name: openiddict-sample-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
